#python code to create seraut input from h5ad files
```{python Note this part is finished by Scanpy}
import scanpy as sc
import pandas as pd
import numpy as np
import squidpy as sq
import matplotlib.pyplot as plt
import seaborn as sns
import os
import gc
import anndata as ad
from matplotlib.backends.backend_pdf import PdfPages

#read in the longitude CosMx dataset that can be downloaded directly from the link: https://figshare.com/s/e8ad68ff0b4627351df0
adata = sc.read_h5ad("~/23_8_6_CosMx_longitudinal.h5ad")

#need to use AUCell to annotate the longitude CosMx dataset

# Extract normalized counts (cells x genes)
norm_matrix = adata.to_df(layer='log_normalized_counts')  # This gives a DataFrame with cell names as index
# reset index to make cell IDs a column
norm_matrix.index.name = "cell_id"
norm_matrix.reset_index(inplace=True)
# Save to CSV
norm_matrix.to_csv("~/normalized_matrix_for_AUCell.csv", index=False)


#also save the raw counts
# Extract normalized counts (cells x genes)
norm_matrix = adata.to_df(layer='raw_counts')  # This gives a DataFrame with cell names as index
# reset index to make cell IDs a column
norm_matrix.index.name = "cell_id"
norm_matrix.reset_index(inplace=True)
# Save to CSV
norm_matrix.to_csv("~/raw_matrix_for_AUCell.csv", index=False)

#also save the metadata for seurat object
adata.obs.to_csv("~/metadata_for_seurat.csv")
```

```{r}
library(dplyr)
library(Seurat)
library(ggplot2)
library(CellChat)
library(AUCell)
library(GSEABase)
library(data.table)
options(future.globals.maxSize = 30 * 1024^3)  # Set to 30 GB
library(scran)
library(SpatialExperiment)
library(nnSVG)
```

```{r create seruat obj}
# Read and preprocess data
raw_1k <- fread("~/raw_matrix_for_AUCell.csv")
raw_1k <- as.data.frame(raw_1k)
rownames(raw_1k) <- raw_1k[[1]]  
raw_1k <- raw_1k[, -1] 

# Create Seurat object
raw_1k_so <- CreateSeuratObject(counts = t(raw_1k))
	
#add metadata
meta <- read.csv("~/metadata_for_seurat.csv", row.names = 1)

# Ensure that rownames match Seurat cell names
meta <- meta[Cells(raw_1k_so), , drop = FALSE]

# Assign metadata
raw_1k_so <- AddMetaData(raw_1k_so, metadata = meta)

#no slide information, process the dataset
raw_1k_so <- NormalizeData(raw_1k_so)
raw_1k_so <- FindVariableFeatures(raw_1k_so)
raw_1k_so <- ScaleData(raw_1k_so)
raw_1k_so <- RunPCA(raw_1k_so)
raw_1k_so <- RunUMAP(raw_1k_so, dims = 1:30)

#--------------------#
#do harmoney workflow
#--------------------#
raw_1k_so[["RNA"]] <- split(raw_1k_so[["RNA"]], f = raw_1k_so$HS_combinebiopsy)
DefaultAssay(raw_1k_so) <- "RNA"
raw_1k_so <- NormalizeData(raw_1k_so)
raw_1k_so <- FindVariableFeatures(raw_1k_so)
raw_1k_so <- ScaleData(raw_1k_so)
raw_1k_so <- RunPCA(raw_1k_so)
raw_1k_so <- IntegrateLayers(object = raw_1k_so, method = HarmonyIntegration, orig.reduction = "pca",
  new.reduction = 'harmony')

raw_1k_so <- RunUMAP(raw_1k_so, reduction = "harmony", dims = 1:30, reduction.name = "umap.harmony")
```

#Gene markers set for each cell types
```{r}

#gene marker sets were obtained from reference datasets/papers mentioned in the paper

scRNAseq_HC_markers_list <- list(

  Myeloid = c(
    "LYZ","TYROBP","FCER1G","HLA-DPB1","HLA-DRA","C1QA","HLA-DQA1","HLA-DRB5","HLA-DRB1",
    "C1QC","C1QB","HLA-DPA1","HLA-DQB1","IL1B","GLUL","COTL1","SLC40A1","CLEC10A","ITGB2",
    "LGALS1","CD14","PSAP","CCL3","HCK","TNFSF13B","CXCL16","MS4A4A","CLEC7A","CSF1R",
    "GPNMB","CD36","CD74","RB1","SAT1","CD68","IGF1","PTGS2","IER3","CD86","CD209",
    "CSF2RA","S100A9","LYN","CD81","CXCL2","CD300A","TIMP1","ICAM1","ENTPD1","BST2"
  ),

  Connective = c(
    "IGFBP7","COL1A2","COL3A1","CXCL14","CALD1","IFITM3","COL6A2","RARRES2","DCN","GPX3",
    "GSN","CFD","COL1A1","LUM","MMP2","COL6A1","TPM2","CXCL12","TM4SF1","BMP4","MYL9","CCL2",
    "SPARCL1","TIMP1","LGALS1","IGFBP6","CCL8","SERPINH1","SNAI2","CCL13","MXRA8","FOXF1",
    "PTGDS","CCL11","MEG3","IGFBP3","VCAN","ACTA2","C11orf96","COL5A1","CAV1","BMP5",
    "COL4A2","PDGFRA","VCAM1","COL18A1","COL14A1","FN1","COL6A3","IL6ST"
  ),

  Granulocyte = c(
    "TPSAB1","HPGDS","CPA3","FCER1G","CLU","GLUL","ANXA1","TYROBP","CTSG","KIT","TPSB2",
    "CD9","KRT1","IL1RL1","STMN1","TSC22D1","DUSP6","TNFSF10","CSF1","BTK","S100A4","AREG",
    "CD63","LMNA","SRGN","NFKBIA","VIM","RGS1","CD69","CD44","JUN","EMP3","TIMP1","DUSP1",
    "RGS2","SAT1","DDIT3","HSP90AB1","FOS","CD37","HSPA1B","HSPA1A","JUNB","CALM2","IGKC",
    "SQSTM1","HSP90B1","XBP1","CD59","RPL22"
  ),

  Neuron = c(
    "CRYAB","CLU","IGFBP7","S100B","SPP1","IFITM3","CD9","CCL2","COL1A2","SPARCL1","GPX3",
    "NRXN1","MYL9","COL18A1","MXRA8","IL11RA","COL1A1","RARRES2","COL9A3","CD59","LGALS1",
    "ANXA2","IFI27","ERBB3","S100A4","S100A10","HLA-DRB1","STMN1","APP","VIM","PSAP","CALM2",
    "HSPA1A","CD63","ATF3","HLA-DPA1","HSP90B1","JUNB","HSPB1","CALM1","LMNA","SOD1","CD47",
    "ZFP36","PTGES3","NOSIP","GSTP1","BST2","MAP1LC3B","TUBB4B"
  ),

  T = c(
    "CD3E","CD3D","CD2","IL32","IL7R","CD52","HCST","PTPRC","ANXA1","CD3G","CCL5","IFITM1",
    "KLRB1","ARHGDIB","S100A4","SPOCK2","CD69","FYN","LTB","CST7","CLEC2D","RORA","GPR183",
    "RAC2","ETS1","SRGN","NKG7","ADGRE5","ITM2A","STAT4","GZMA","CD48","CD8A","RUNX3","ICOS",
    "GATA3","DUSP2","CRIP1","IL2RG","NR3C1","JAK1","STAT3","CTSW","RGCC","PTPRCAP","ITGB2",
    "RGS1","ZFP36","CCL4","KLF2"
  ),

  NK = c(
    "IL32","CD2","CCL5","ANXA1","IL7R","CXCR4","CD52","KLRB1","LTB","HCST","S100A4","CD69",
    "ARHGDIB","PTPRC","CST7","KRT10","SRGN","FYN","CD3G","CD3D","NKG7","SPOCK2","RGCC","GPR183",
    "DUSP2","DUSP5","RORA","BTG1","JUNB","B2M","CLEC2D","IFITM1","PTPRCAP","RPL37","ITM2A",
    "ICAM3","CALM1","DUSP1","CD48","CLEC2B","RGS1","HLA-E","BAX","RPS4Y1","FOS","CALM3","CD53",
    "IL2RG","STAT3","CD44"
  ),

  B = c(
    "MS4A1","HLA-DRA","HLA-DPB1","HLA-DRB1","VPREB3","HLA-DPA1","HLA-DQA1","HLA-DQB1","CD79A",
    "CD83","HLA-DRB5","LTB","CD37","CXCR4","CD52","IGHM","CD74","CD19","SELL","FCRLA","IGHD",
    "CD53","TCL1A","LYN","GPR183","CXCR5","CD24","P2RX5","KLF2","CCR7","CD40","RAC2","CD55",
    "CD48","IL16","SMARCB1","TNFRSF13B","ATM","BTG1","CSK","PARP1","RPL22","RPL37","RPL21",
    "RPL34","RPL32","MALAT1","JAK1","RGS2","CD47"
  ),

  Plasma = c(
    "MZB1","TNFRSF17","CD79A","FKBP11","XBP1","CD27","IGKC","HSP90B1","CCR10","DUSP5","IGHA1",
    "TNFRSF18","IGHM","TNFRSF13B","CD38","JCHAIN","PNOC"
  ),


  Endothelial = c(
    "SPARCL1","RAMP2","CAV1","IGFBP7","TM4SF1","RAMP3","IFITM3","CLEC14A","IFI27","ENG","VWF",
    "ESAM","FABP5","GSN","MGP","TNFSF10","CD59","TGFBR2","APP","TSC22D1","CD36","CD34","ACVRL1",
    "GAS6","FLT1","CDH5","IL3RA","COL4A1","COL15A1","COL4A2","KDR","ICAM1","DUSP6","LIFR","TIE1",
    "IGFBP3","ACE","IFIT1","ITGA5","CLU","CCND1","TEK","ITGA6","COL18A1","ITGA1","BST2",
    "ENTPD1","RGCC","STMN1","NR1H2"
  )
)

scRNAseq_inflamed_markers_list <- list(

  Myeloid = c(
    "TYROBP","S100A9","FCER1G","IL1B","LYZ","SOD2","S100A8","GLUL","CXCL8","CD14","FPR1","IL1RN",
    "LYN","SERPINA1","PTGS2","CLEC7A","HCK","CSF3R","ICAM1","TNFSF13B","HLA-DRA","C1QA","CCL3",
    "C1QB","SAT1","CXCL16","HLA-DPB1","C1QC","CSF2RB","HLA-DRB1","CD68","CLEC4A","ITGAX","HCAR3",
    "TLR4","BID","HLA-DPA1","OSM","FCGR3A","PSAP","CCR1","ADGRE2","TNFAIP6","CD55","DUSP6",
    "HLA-DRB5","LGALS9","SYK","CYSTM1","NEAT1"
  ),

  Connective = c(
    "COL3A1","CALD1","COL1A2","COL6A2","COL1A1","TPM2","DCN","COL6A1","RARRES2","LUM","COL6A3",
    "MMP2","MYL9","C11orf96","CXCL14","COL5A2","IGFBP5","CFD","COL5A1","PDGFRA","IGFBP6","MEG3",
    "COL18A1","COL14A1","TAGLN","CDH11","CCL2","FN1","MXRA8","DDR2","BGN","COL12A1","FOXF1",
    "FGF7","ACTA2","BMP4","PTGDS","CXCL12","SNAI2","MRC2","CCL11","WNT5A","CHI3L1","GPX3",
    "OSMR","HGF","NRG1","WNT2B","HSD17B2","MMP1"
  ),

  Granulocyte = c(
    "TPSAB1","CPA3","HPGDS","FCER1G","CLU","ANXA1","CTSG","TYROBP","CD9","KIT","GLUL","KRT1",
    "IL1RL1","TPSB2","CD69","LMNA","S100A4","TNFSF10","CD63","SRGN","DUSP6","STMN1","TSC22D1",
    "THBS1","NFKBIA","TIMP1","RGS1","VIM","AHR","RGCC","JUN","MALAT1","CD44","EMP3","HSPA1A",
    "HSP90AA1","KRT10","CALM2","NEAT1","SAT1","CALM3","LGALS1","GADD45B","MT2A","SEC61G"
  ),

  Neuron = c(
    "CRYAB","S100B","IGFBP7","CLU","NRXN1","SPARCL1","CD9","IFITM3","DST","CCL2","GSN","COL18A1",
    "SPP1","PDGFA","ERBB3","COL8A1","COL9A3","MXRA8","ITGB8","ITGB4","PDGFB","NGFR","NRXN3",
    "COL14A1","COL5A3","ALCAM","IL11RA","FGF2","SERPINA3","MYL9","TNFRSF12A","LGALS3BP","CD59",
    "AHR","ANXA2","IFI27","COL5A1","PTK2","GPNMB","ADIRF","CCND1","IL6ST","TGFBR2","VIM",
    "NDRG1","SERPINH1","S100A6","LAMP2","IGFBP6","YBX3"
  ),

  T = c(
    "CD3E","CD3D","IL32","CD2","CD3G","PTPRC","HCST","SPOCK2","ARHGDIB","CST7","CCL5","KLRB1",
    "FYN","IL7R","LTB","RAC2","S100A4","CD8A","NKG7","GZMA","IL2RG","IFITM1","SRGN","ITM2A",
    "CLEC2D","RORA","COTL1","TIGIT","DUSP2","CD8B","ICOS","ETS1","IL2RB","RUNX3","CTSW",
    "STAT4","DUSP4","FYB1","TNFRSF1B","ANXA1","CRIP1","CLEC2B","ADGRE5","EZR","NR3C1","CCL4",
    "HLA-A","HMGB2","SIGIRR","MZT2A"
  ),

  NK = c(
    "IL32","KLRB1","CD2","LTB","CD52","CD3D","CCL5","HCST","CXCR4","IL7R","CD69","PTPRC",
    "ARHGDIB","SRGN","CST7","NKG7","CD3G","SPOCK2","DUSP2","S100A4","BTG1","PTPRCAP","FYN",
    "CD164","RGCC","ITM2A","GPR183","CD48","HLA-A","RPL32","JUNB","MALAT1","RPL34","B2M",
    "ANXA1","RPL21","RAC2","RPL22","IL2RG","PTGES3","CALM3","ICAM3","CRIP1","CALM1","RGS1",
    "JAK1","ZFP36","STAT3","SOD1","RPS4Y1"
  ),

  B = c(
    "MS4A1","HLA-DRA","HLA-DPB1","HLA-DQA1","HLA-DRB1","HLA-DPA1","HLA-DQB1","CD37","CD83",
    "VPREB3","CD79A","CD52","LTB","CXCR4","HLA-DRB5","CD74","TCL1A","CD69","IGHD","CD19",
    "SELL","CD48","CD53","BTG1","CD40","PLAC8","PTPRCAP","LYN","RAC2","EZR","CSK","KLF2",
    "GPR183","COTL1","RPL22","RPL37","RPL34","RPL32","MALAT1","RPL21","PARP1","HLA-E",
    "PTPRC","CD55","JUNB","MAP1LC3B","CD47","CD164","RGS2","RPS4Y1"
  ),

  Plasma = c(
    "MZB1","FKBP11","CD79A","TNFRSF17","XBP1","IGHG1","CD27","HSP90B1","IGHG2","IGKC",
    "IGHA1","DUSP5","SEC61G","CD38","HSPA1B","IGHM","JCHAIN","PNOC","GAS6","HSPA1A",
    "ST6GAL1","HSPB1"
  ),

  Endothelial = c(
    "SPARCL1","RAMP2","VWF","IGFBP7","MGP","TM4SF1","RAMP3","ENG","CLEC14A","CAV1","COL4A1",
    "COL15A1","COL4A2","TGFBR2","ESAM","APP","CDH5","CD34","GSN","ACVRL1","FLT1","BMPR2",
    "ITGA6","KDR","IL3RA","SERPINH1","PECAM1","ADGRL4","ITGA5","TIE1","INSR","ADGRF5","TEK",
    "EFNA1","IGFBP3","ITGA1","LIFR","EFNB2","MECOM","FZD4","PDGFB","EPHB4","IL33","PTK2",
    "JAG1","FZD6","NPR1","ADGRL2","ADGRG1","ANGPT2"
  )
)

scRNAseq_non_inflamed_markers_list <- list(

  Myeloid = c(
    "TYROBP","LYZ","FCER1G","HLA-DPB1","HLA-DQA1","HLA-DRA","C1QA","HLA-DPA1","HLA-DRB1",
    "C1QB","C1QC","HLA-DQB1","HLA-DRB5","IL1B","CD83","CD14","CCL3","COTL1","SLC40A1",
    "CLEC10A","CLEC7A","PSAP","GLUL","TNFSF13B","MS4A4A","CSF1R","CD74","HCK","CD4",
    "PTGS2","RB1","CXCL16","CD86","SAT1","CD36","GPNMB","CCL4","AHR","CXCL2","LYN",
    "CLEC4A","S100A9","CD209","IGF1","CD68","CSF2RA","CD163","MMP12","CD300A","CXCL3"
  ),

  Connective = c(
    "CALD1","IGFBP7","COL3A1","COL1A2","COL6A2","DCN","CXCL14","LUM","COL1A1","IFITM3",
    "RARRES2","CFD","TPM2","COL6A1","MMP2","MYL9","FN1","CXCL12","BMP4","TIMP1","CCL2",
    "IGFBP6","GPX3","MEG3","VCAN","COL6A3","IGFBP3","SERPINH1","MXRA8","TAGLN","PDGFRA",
    "C11orf96","ACTA2","COL14A1","COL5A1","COL4A2","FOXF1","VCAM1","COL5A2","SNAI2",
    "IGFBP5","IL1R1","MGP","CCL11","FGF7","CDH11","DDR2","PTGDS","COL4A1","WNT2B"
  ),

  Granulocyte = c(
    "TPSAB1","CPA3","HPGDS","FCER1G","ANXA1","CTSG","TYROBP","CLU","KIT","CD69","GLUL",
    "SRGN","CD9","S100A4","KRT1","TPSB2","STMN1","NFKBIA","IL1RL1","DUSP6","RGS1","LMNA",
    "VIM","TNFSF10","CD83","CD44","IL2RG","CD63","JUN","HSP90AB1","EMP3","SOD1","ARHGDIB",
    "TSC22D1","MALAT1","GSTP1","RPL34","DUSP1","FOS","HSP90AA1","CD59","SAT1","SQSTM1",
    "HSPA1A","CALM3","RGS2","GADD45B","BST2","HSPA1B","CALM2"
  ),

  Neuron = c(
    "CRYAB","CLU","S100B","IGFBP7","NRXN1","SPP1","CD9","SPARCL1","IFITM3","COL1A2",
    "CCL2","COL18A1","COL9A3","MXRA8","ERBB3","TNFAIP6","COL8A1","IL11RA","DST","GSN",
    "LGALS1","CD59","MT2A","COL4A1","S100A4","VIM","ANXA2","ANXA1","SOX4","COL4A2",
    "APP","ADIRF","ITGB1","IER3","HSPA1A","STMN1","CD81","PSAP","HSPB1","TGFBR2",
    "JUN","FOS","LAMP2","NDRG1","GSTP1","IL6ST","HMGB2","STAT3","BST2","KRT10"
  ),

  T = c(
    "CD3E","CD3D","IL32","CD52","CD2","LTB","HCST","ARHGDIB","PTPRC","CD3G","IL7R",
    "CXCR4","KLRB1","CCL5","S100A4","CD48","CD69","PTPRCAP","RAC2","CD37","SPOCK2","SRGN",
    "CST7","COTL1","NKG7","ANXA1","GZMA","FYN","RORA","IL2RG","ITM2A","CD53","BTG1",
    "ITGB2","GPR183","CTSW","DUSP2","RGCC","HLA-E","CALM1","HLA-A","RPL34","CD27",
    "CLEC2B","NOSIP","CD44","TGFB1","RGS1","ICAM3","CRIP1"
  ),

  NK = c(
    "IL32","KLRB1","CD52","CD2","HCST","CCL5","CD3D","LTB","CXCR4","PTPRC","ARHGDIB",
    "IL7R","SRGN","S100A4","CD69","CST7","NKG7","GZMA","CD3G","PTPRCAP","ANXA1","FYN",
    "CD48","CD37","DUSP2","RAC2","GPR183","BTG1","RGCC","MALAT1","B2M","ITM2A","HLA-A",
    "COTL1","CD53","RPL32","PTGES3","HLA-B","HLA-E","RGS1","IL2RG","CD47","JUNB","HLA-C",
    "MZT2A","CALM3","CLEC2B","CALM1","ICAM3","CD44"
  ),

  B = c(
    "MS4A1","HLA-DPB1","HLA-DRA","HLA-DQA1","HLA-DPA1","HLA-DRB1","HLA-DQB1","CD79A",
    "CD37","LTB","CD52","CXCR4","VPREB3","HLA-DRB5","CD83","CD74","TCL1A","IGHD","CD69",
    "SELL","ARHGDIB","CD53","CD19","PTPRCAP","FCRLA","RAC2","PTPRC","CD48","GPR183",
    "CD40","BTG1","KLF2","PLAC8","RPL37","COTL1","RPL32","HLA-E","RPL21","ARF1","RPL22",
    "HLA-B","PARP1","CD55","EZR","MAP1LC3B","SMARCB1","ICAM3","JAK1","CD44","RGS2"
  ),

  Plasma = c(
    "MZB1","TNFRSF17","CD79A","FKBP11","XBP1","CD27","IGKC","DUSP5","HSP90B1","CCR10",
    "IFNAR2","SEC61G","ICAM2","IGHA1","IGHM","TNFRSF13B","CD38","HSPA1B","IGHG1","PNOC",
    "IFNAR1","HSPA1A","JCHAIN"
  ),

  Endothelial = c(
    "RAMP2","SPARCL1","RAMP3","TM4SF1","CAV1","CLEC14A","IGFBP7","ENG","ESAM","TGFBR2",
    "VWF","MGP","IFITM3","FABP5","CD34","CD59","ACVRL1","FLT1","TSC22D1","ICAM2","CDH5",
    "COL4A1","ADIRF","IL3RA","COL15A1","COL4A2","ITGA6","CD36","KDR","EFNA1","LIFR",
    "NDRG1","BMPR2","ICAM1","ENTPD1","TIE1","TEK","ITGA1","COL18A1","ITGA5","IL33",
    "CLU","MECOM","INSR","PECAM1","EFNB2","ADGRL4","TSHZ2","MX1","RGCC"
  )
)
```

#do the AUCell annotation
```{r}
#----------------#
#----------------#
#use panCK >= 5000 to gate select epithelial cells 
raw_1k_so$Epi_panCK <- ifelse(raw_1k_so$Max.PanCK >= 5000, "Epi", "NonEpi")

#seperate the longitude samples into HC, inflamed and non-inflamed
Idents(raw_1k_so) <- "Condition"
raw_1k_so_HC <- subset(raw_1k_so, idents = "HC")
raw_1k_so_inflamed <- subset(raw_1k_so, idents = c("PRE_VDZ_Responder", "PRE_VDZ_Non-responder", "VDZ_POST_Non-responder"))
raw_1k_so_noninflamed <- subset(raw_1k_so, idents = "VDZ_POST_Responder")



#Do AUCell labeling
# do non-inflamed 
exprMat <- as.matrix(GetAssayData(raw_1k_so_noninflamed, slot = "data", assay = "RNA"))
cells_rankings <- AUCell_buildRankings(exprMat, plotStats = FALSE)
cells_AUC <- AUCell_calcAUC(scRNAseq_non_inflamed_markers_list, cells_rankings,verbose = T)
#cells_assignment <- AUCell_exploreThresholds(cells_AUC)
auc_mat <- as.data.frame(getAUC(cells_AUC))
cell_type_annotation <- rownames(auc_mat)[apply(auc_mat, 2, which.max)]
names(cell_type_annotation) <- colnames(auc_mat)
raw_1k_so_noninflamed$AUCell_1 <- cell_type_annotation

raw_1k_so_noninflamed$AUCell <- ifelse(raw_1k_so_noninflamed$Max.PanCK >= 5000, "Epithelial", raw_1k_so_noninflamed$AUCell_1)


#do inflamed
exprMat <- as.matrix(GetAssayData(raw_1k_so_inflamed, slot = "data", assay = "RNA"))
cells_rankings <- AUCell_buildRankings(exprMat, plotStats = FALSE)
cells_AUC <- AUCell_calcAUC(scRNAseq_inflamed_markers_list, cells_rankings,verbose = T)
#cells_assignment <- AUCell_exploreThresholds(cells_AUC)
auc_mat <- as.data.frame(getAUC(cells_AUC))
cell_type_annotation <- rownames(auc_mat)[apply(auc_mat, 2, which.max)]
names(cell_type_annotation) <- colnames(auc_mat)
raw_1k_so_inflamed$AUCell_1 <- cell_type_annotation

raw_1k_so_inflamed$AUCell <- ifelse(raw_1k_so_inflamed$Max.PanCK >= 5000, "Epithelial", raw_1k_so_inflamed$AUCell_1)


#do HC
exprMat <- as.matrix(GetAssayData(raw_1k_so_HC, slot = "data", assay = "RNA"))
cells_rankings <- AUCell_buildRankings(exprMat, plotStats = FALSE)
cells_AUC <- AUCell_calcAUC(scRNAseq_HC_markers_list, cells_rankings,verbose = T)
#cells_assignment <- AUCell_exploreThresholds(cells_AUC)
auc_mat <- as.data.frame(getAUC(cells_AUC))
cell_type_annotation <- rownames(auc_mat)[apply(auc_mat, 2, which.max)]
names(cell_type_annotation) <- colnames(auc_mat)
raw_1k_so_HC$AUCell_1 <- cell_type_annotation

raw_1k_so_HC$AUCell <- ifelse(raw_1k_so_HC$Max.PanCK >= 5000, "Epithelial", raw_1k_so_HC$AUCell_1)


#---------------
#---------------
#merge the three annotated objects back together
#add the AUCell annotatoin back to the Seurat obj
list_10x_merge_AUCell <- merge(raw_1k_so_HC, y = c(raw_1k_so_inflamed, raw_1k_so_noninflamed))

raw_1k_so <- AddMetaData(raw_1k_so, metadata  = list_10x_merge_AUCell@meta.data, col.name = "AUCell")

#-----------------
#-----------------
#add SPP1 information
spp1_expr <- FetchData(raw_1k_so, vars = "SPP1")
raw_1k_so$SPP1_status <- ifelse(spp1_expr$SPP1 > 0, "SPP1+", "SPP1-")
raw_1k_so$AUCell_SPP1 <- ifelse(raw_1k_so$SPP1_status == "SPP1+" & raw_1k_so$AUCell == "Myeloid", "Myeloid_SPP1+",
                                     ifelse(raw_1k_so$SPP1_status == "SPP1-" & raw_1k_so$AUCell == "Myeloid", "Myeloid_SPP1-",
                                            raw_1k_so$AUCell))


#------------------#
#------------------#
#do dot plot plot for figure 4B
Idents(raw_1k_so) <- "AUCell"
raw_1k_so_myeloid <- subset(raw_1k_so, idents = "Myeloid")

#subset to remove HC and post-treatment
Idents(raw_1k_so_myeloid) <- "Condition"
raw_1k_so_myeloid_noHC <- subset(raw_1k_so_myeloid, idents = c("PRE_VDZ_Non-responder", "PRE_VDZ_Responder"))

DotPlot(raw_1k_so_myeloid_noHC, group.by = "SPP1_status", features = c("ANGIOGENESIS_NR_up_all1",ANGIOGENESIS_NR_up_all,"ITGA4","ITGB7", "MMP19", "CCL2"), cols = c("lightgrey","red"))+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

#check cell numbers
table(raw_1k_so_myeloid_noHC$SPP1_status)
```

#cellchat CCI analysis for figure 4D
```{r}
#firstly do SCT of the dataset
raw_1k_so <- SCTransform(raw_1k_so)

#seperate the data into HC, responder, non-responder
Idents(raw_1k_so) <- "Condition"
raw_1k_so_control <- subset(raw_1k_so, idents = "HC")
raw_1k_so_pre_res <- subset(raw_1k_so, idents = "PRE_VDZ_Responder")
raw_1k_so_pre_nonres <- subset(raw_1k_so, idents = "PRE_VDZ_Non-responder")
raw_1k_so_post_res <- subset(raw_1k_so, idents = "VDZ_POST_Responder")
raw_1k_so_post_nonres <- subset(raw_1k_so, idents = "VDZ_POST_Non-responder")



list_10x <- SplitObject(raw_1k_so, split.by = "HS_combinebiopsy")

#unique(raw_1k_so$HS_combinebiopsy)
#  [1] "FOV_01_10_40_53_HS34_VDZ_POST_Responder"            "FOV_03_11_54_58_76_HS33_HC"                        
#  [3] "FOV_12_55_65_HS32_VDZ_RC_POST_Mayo0_Responder"      "FOV_04_13_44_56_64_HS32_VDZ_PRE_Responder"         
#  [5] "FOV_05_14_45_57_81_HS31_HC"                         "FOV_15_59_HS50_VDZ_RS_POST_Mayo2_Non-responder"    
#  [7] "FOV_16_60_HS50_VDZ_RS_PRE_Mayo2_Non-responder"      "FOV_17_74_HS49_VDZ_R_POST_Mayo3_Non-responder"     
#  [9] "FOV_18_75_HS49_VDZ_RS_PRE_Mayo2_Non-responder"      "FOV_19_20_28_29_HS44_VDZ_PRE_Responder"            
# [11] "FOV_02_41_62_80_HS34_VDZ_C_PRE_Mayo2_Responder"     "FOV21_HS48_VDZ_C_POST_1_Mayo2_Non-responder"       
# [13] "FOV_22_61_HS47_VDZ_R_POST_Mayo3_Non-responder"      "FOV_24_73_HS46_VDZ_LC_PRE_Mayo3_Non-responder"     
# [15] "FOV25_HS41_HC_2"                                    "FOV26_HS45_VDZ_R_POST_1_Mayo3_Non-responder"       
# [17] "FOV27_HS45_VDZ_RC_PRE_1_Mayo0_Non-responder"        "FOV30_HS43_HC_1"                                   
# [19] "FOV31_HS42_HC_1"                                    "FOV_06_32_35_48_67_71_72_78_HS38_VDZ_PRE_Responder"
# [21] "FOV_34_46_HS39_HC"                                  "FOV_07_36_49_66_70_77_HS37_HC"                     
# [23] "FOV_37_50_HS36_VDZ_POST_Responder"                  "FOV_09_38_HS40_HC"                                 
# [25] "FOV47_HS38_VDZ_RC_POST_1_Mayo0_Responder"           "FOV_08_51_63_79_HS36_VDZ_RS_PRE_Mayo3_Responder"

#---#
##1## read counts matrix
#---#
#obtain the input data of each sample
data.input_list <- list()
for(i in 1:26){
  data.input_list[[i]] <- Seurat::GetAssayData(list_10x[[i]], slot = "data", assay = "SCT")
}
#rename the cells of each samples
for(i in 1:26){
  colnames(data.input_list[[i]]) <- paste0("A",i,"_", colnames(data.input_list[[i]]))
}


#generat the read maxtirx (SCT in this case) input for repsonders and non-responders
data.input.control <- cbind(data.input_list[[2]], data.input_list[[5]],data.input_list[[15]],data.input_list[[18]],
                            data.input_list[[19]],data.input_list[[21]],data.input_list[[22]], data.input_list[[24]])
data.input.pre.responder <- cbind(data.input_list[[4]],data.input_list[[10]],data.input_list[[11]],data.input_list[[20]],
                                  data.input_list[[26]])
data.input.pre.non_responder <- cbind(data.input_list[[7]],data.input_list[[9]],data.input_list[[14]],data.input_list[[17]])
                                     
data.input.post.responder <- cbind(data.input_list[[1]], data.input_list[[3]],data.input_list[[23]],data.input_list[[25]])
data.input.post.non_responder <- cbind(data.input_list[[6]],data.input_list[[8]],data.input_list[[12]],data.input_list[[13]],
                                       data.input_list[[16]])



#---#
##2## meta data
#---#
#generate the metadata for each sample and then for responders and non-responders
meta.input_list <- list()
for(i in 1:26){
  Idents(list_10x[[i]]) <- "AUCell_SPP1"
  meta.input_list[[i]] <- data.frame(labels = Idents(list_10x[[i]]), samples = paste("A",i,sep = ""))
}
meta.control <-  rbind(meta.input_list[[2]], meta.input_list[[5]],meta.input_list[[15]],meta.input_list[[18]],
                            meta.input_list[[19]],meta.input_list[[21]],meta.input_list[[22]], meta.input_list[[24]])
meta.pre.responder <- rbind(meta.input_list[[4]],meta.input_list[[10]],meta.input_list[[11]],meta.input_list[[20]],
                                  meta.input_list[[26]])
meta.pre.non_responder <- rbind(meta.input_list[[7]],meta.input_list[[9]],meta.input_list[[14]],meta.input_list[[17]])
meta.post.responder <- rbind(meta.input_list[[1]], meta.input_list[[3]],meta.input_list[[23]],meta.input_list[[25]])
meta.post.non_responder <- rbind(meta.input_list[[6]],meta.input_list[[8]],meta.input_list[[12]],meta.input_list[[13]],
                                       meta.input_list[[16]])


rownames(meta.control) <- colnames(data.input.control)
rownames(meta.pre.responder) <- colnames(data.input.pre.responder)
rownames(meta.pre.non_responder) <- colnames(data.input.pre.non_responder)
rownames(meta.post.responder) <- colnames(data.input.post.responder)
rownames(meta.post.non_responder) <- colnames(data.input.post.non_responder)

#factor them
meta.control$labels <- factor(meta.control$labels, levels = c("Epithelial","Endothelial","Connective","B","Plasma","T","NK","Granulocyte","Neuron","Myeloid_SPP1-", "Myeloid_SPP1+"))
meta.pre.responder$labels <- factor(meta.pre.responder$labels, levels = c("Epithelial","Endothelial","Connective","B","Plasma","T","NK","Granulocyte","Neuron","Myeloid_SPP1-", "Myeloid_SPP1+"))
meta.pre.non_responder$labels <- factor(meta.pre.non_responder$labels, , levels = c("Epithelial","Endothelial","Connective","B","Plasma","T","NK","Granulocyte","Neuron","Myeloid_SPP1-", "Myeloid_SPP1+"))
meta.post.responder$labels <- factor(meta.post.responder$labels, levels = c("Epithelial","Endothelial","Connective","B","Plasma","T","NK","Granulocyte","Neuron","Myeloid_SPP1-", "Myeloid_SPP1+"))
meta.post.non_responder$labels <- factor(meta.post.non_responder$labels, , levels = c("Epithelial","Endothelial","Connective","B","Plasma","T","NK","Granulocyte","Neuron","Myeloid_SPP1-", "Myeloid_SPP1+"))

meta.control$samples <- factor(meta.control$samples, levels = c("A2","A5","A15","A18","A19","A21","A22","A24"))
meta.pre.responder$samples <- factor(meta.pre.responder$samples, levels = c("A4","A10","A11","A20","A26"))
meta.pre.non_responder$samples <- factor(meta.pre.non_responder$samples, levels = c("A7","A9","A14","A17"))
meta.post.responder$samples <- factor(meta.post.responder$samples, levels = c("A1","A3","A23","A25"))
meta.post.non_responder$samples <- factor(meta.post.non_responder$samples, levels = c("A6","A8","A12","A13","A16"))

#---#
##3## the coordinates matrix
#---#
coordinates.input_list <- list()

for(i in 1:26){
  df <- list_10x[[i]]@meta.data
  df <- df[,c("CenterX_global_px", "CenterY_global_px")]
  #df$x_slide_mm <- df$x_slide_mm*1000
  #df$y_slide_mm <- df$y_slide_mm*1000
  coordinates.input_list[[i]] <- df
}

spatial.locs.control <- rbind(coordinates.input_list[[2]], coordinates.input_list[[5]],coordinates.input_list[[15]],coordinates.input_list[[18]],
                            coordinates.input_list[[19]],coordinates.input_list[[21]],coordinates.input_list[[22]], coordinates.input_list[[24]])
spatial.locs.pre.res <- rbind(coordinates.input_list[[4]],coordinates.input_list[[10]],coordinates.input_list[[11]],coordinates.input_list[[20]],
                                  coordinates.input_list[[26]])
spatial.locs.pre.nonres <- rbind(coordinates.input_list[[7]],coordinates.input_list[[9]],coordinates.input_list[[14]],coordinates.input_list[[17]])
spatial.locs.post.res <- rbind(coordinates.input_list[[1]],coordinates.input_list[[3]],
                                  coordinates.input_list[[23]],coordinates.input_list[[25]])
spatial.locs.post.nonres <- rbind(coordinates.input_list[[6]],coordinates.input_list[[8]],coordinates.input_list[[12]],
                                  coordinates.input_list[[13]],coordinates.input_list[[16]])


rownames(spatial.locs.control) <- colnames(data.input.control)
rownames(spatial.locs.pre.res) <- colnames(data.input.pre.responder)
rownames(spatial.locs.pre.nonres) <- colnames(data.input.pre.non_responder)
rownames(spatial.locs.post.res) <- colnames(data.input.post.responder)
rownames(spatial.locs.post.nonres) <- colnames(data.input.post.non_responder)

#turn into matrix
spatial.locs.control <- as.matrix(spatial.locs.control)
spatial.locs.pre.res <- as.matrix(spatial.locs.pre.res)
spatial.locs.pre.nonres <- as.matrix(spatial.locs.pre.nonres)
spatial.locs.post.res <- as.matrix(spatial.locs.post.res)
spatial.locs.post.nonres <- as.matrix(spatial.locs.post.nonres)

#---#
##4## create the coordinates scale factor dataframe
#---#
conversion.factor = 0.16
#d = computeCellDistance(spatial.locs.res) #Error: cannot allocate vector of size 2194.8 Gb ...NVM
spot.size = 1.5 # ~1.5um per cell which is 0.0015mm per cell
spatial.factors = data.frame(ratio = conversion.factor, tol = spot.size/2)

spatial.factors <- rbind(spatial.factors, spatial.factors,spatial.factors,spatial.factors,spatial.factors,spatial.factors,spatial.factors,spatial.factors,spatial.factors)

rownames(spatial.factors) <- paste0("A", c(1:9))

#---#
##5## create the final cellchat objects
#---#
cellchat_CosMx_control <- createCellChat(object = data.input.control, meta = meta.control, group.by = "labels",
                           datatype = "spatial", coordinates = spatial.locs.control, spatial.factors = spatial.factors[c(1:8),])

cellchat_CosMx_pre_res <- createCellChat(object = data.input.pre.responder, meta = meta.pre.responder, group.by = "labels",
                           datatype = "spatial", coordinates = spatial.locs.pre.res, spatial.factors = spatial.factors[c(1:5),])

cellchat_CosMx_pre_nonres <- createCellChat(object = data.input.pre.non_responder, meta = meta.pre.non_responder, group.by = "labels",
                           datatype = "spatial", coordinates = spatial.locs.pre.nonres, spatial.factors = spatial.factors[c(1:4),])

cellchat_CosMx_post_res <- createCellChat(object = data.input.post.responder, meta = meta.post.responder, group.by = "labels",
                           datatype = "spatial", coordinates = spatial.locs.post.res, spatial.factors = spatial.factors[c(1:4),])

cellchat_CosMx_post_nonres <- createCellChat(object = data.input.post.non_responder, meta = meta.post.non_responder, group.by = "labels",
                           datatype = "spatial", coordinates = spatial.locs.post.nonres, spatial.factors = spatial.factors[c(1:5),])

#--------------------#
#--------------------#
#continue the CCI analysis

CellChatDB <- CellChatDB.human # use CellChatDB.human if running on human data
# use a subset of CellChatDB for cell-cell communication analysis
CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling", key = "annotation") # use Secreted Signaling
# set the used database in the object
cellchat_CosMx_pre_res@DB <- CellChatDB.use
cellchat_CosMx_pre_nonres@DB <- CellChatDB.use
cellchat_CosMx_post_res@DB <- CellChatDB.use
cellchat_CosMx_post_nonres@DB <- CellChatDB.use

#do merged cellchat
object.list <- list(pre_responder = cellchat_CosMx_pre_res, pre_non_responder = cellchat_CosMx_pre_nonres,
                    post_responder = cellchat_CosMx_post_res, post_non_responder = cellchat_CosMx_post_nonres)
for (i in 1:4){
  object.list[[i]] <- subsetData(object.list[[i]]) # This step is necessary even if using the whole database
#future::plan("multisession", workers = 4) 
object.list[[i]] <- identifyOverExpressedGenes(object.list[[i]])
object.list[[i]] <- identifyOverExpressedInteractions(object.list[[i]])

object.list[[i]] <- computeCommunProb(object.list[[i]], type = "truncatedMean", trim = 0.1, 
                              distance.use = FALSE, interaction.range = 250, scale.distance = NULL,
                              contact.dependent = TRUE, contact.range = 100) 
object.list[[i]] <- filterCommunication(object.list[[i]], min.cells = 10)
object.list[[i]] <- computeCommunProbPathway(object.list[[i]])
object.list[[i]] <- aggregateNet(object.list[[i]])
}

object.list[[1]] <- netAnalysis_computeCentrality(object.list[[1]], slot.name = "netP")
object.list[[2]] <- netAnalysis_computeCentrality(object.list[[2]], slot.name = "netP")
object.list[[3]] <- netAnalysis_computeCentrality(object.list[[3]], slot.name = "netP")
object.list[[4]] <- netAnalysis_computeCentrality(object.list[[4]], slot.name = "netP")

cellchat <- mergeCellChat(object.list, add.names = names(object.list))
#cellchat <- mergeCellChat(list(object.list[[1]], object.list[[2]]), add.names = c("pre_responder","pre_non_responder"))

#do the scatter plot
num.link <- sapply(object.list, function(x) {rowSums(x@net$count) + colSums(x@net$count)-diag(x@net$count)})
weight.MinMax <- c(min(num.link), max(num.link)) # control the dot size in the different datasets
gg <- list()
for (i in 1:length(object.list)) {
  gg[[i]] <- netAnalysis_signalingRole_scatter(object.list[[i]], title = names(object.list)[i], weight.MinMax = weight.MinMax,dot.size = c(4, 12))
}
#> Signaling role analysis on the aggregated cell-cell communication network from all signaling pathways
#> Signaling role analysis on the aggregated cell-cell communication network from all signaling pathways
patchwork::wrap_plots(plots = gg)
p1 <- gg[[1]]+coord_cartesian(xlim = c(0, 0.15), ylim = c(0, 0.15)) #pre-res
p2 <- gg[[2]]+coord_cartesian(xlim = c(0, 0.15), ylim = c(0, 0.15)) #pre-nonres
p3 <- gg[[3]]+coord_cartesian(xlim = c(0, 0.2), ylim = c(0, 0.2)) #post-res
p4 <- gg[[4]]+coord_cartesian(xlim = c(0, 0.2), ylim = c(0, 0.2)) #post-nonres

p_list <- list(p1,p2,p3,p4)

for (i in 1:4) {
pdf(paste0(i,"_plot_panCKEpi.pdf"), width = 7, height = 7)
print(p_list[[i]])
dev.off()
}
```

#nnSVG 
```{r}
unique(raw_1k_so$HS_combinefov)

# fov_list <- c("FOV16_HS50_VDZ_RS_PRE_1_Mayo2_Non-responder", "FOV60_HS50_VDZ_RS_PRE_2_Mayo2_Non-responder",
#               "FOV18_HS49_VDZ_RS_PRE_1_Mayo2_Non-responder","FOV75_HS49_VDZ_RS_PRE_2_Mayo2_Non-responder",
#               "FOV24_HS46_VDZ_LC_PRE_1_Mayo3_Non-responder", "FOV73_HS46_VDZ_LC_PRE_2_Mayo3_Non-responder",
#               "FOV13_HS32_VDZ_sigm_PRE_3_Mayo1_Responder", "FOV56_HS32_VDZ_sigm_PRE_1_Mayo1_Responder",
#               "FOV64_HS32_VDZ_sigm_PRE_2_Mayo1_Responder", "FOV19_HS44_VDZ_LC_PRE_2_Mayo0_Responder",
#               "FOV02_HS34_VDZ_C_PRE_1_Mayo2_Responder", "FOV41_HS34_VDZ_C_PRE_3_Mayo2_Responder")
#               #"FOV04_HS32_VDZ_RS_PRE_4_Mayo2_Responder","FOV19_HS44_VDZ_LC_PRE_2_Mayo0_Responder",
#               #"FOV02_HS34_VDZ_C_PRE_1_Mayo2_Responder", "FOV06_HS38_VDZ_AC_PRE_3_Mayo2_Responder")
Idents(raw_1k_so) <- "Condition"
raw_1k_so_sub <- subset(raw_1k_so, idents = c( "PRE_VDZ_Responder", "PRE_VDZ_Non-responder"))
fov_list <- unique(raw_1k_so_sub$HS)
#need to subset to remove epithelials
Idents(raw_1k_so_sub) <- "AUCell"
raw_1k_so_sub <- subset(raw_1k_so_sub, idents = "Epithelial", invert = T)

final_df <- list()  # initialize an empty list to store dataframes
for (fov in c(fov_list[1:7], fov_list[9:32])){ #8 returns error
  Idents(raw_1k_so_sub) <- "HS"
  seu <- subset(raw_1k_so_sub, idents = fov)
  #subset to remove epithelial cells
  #Idents(seu) <- "AUCell"
  #seu <- subset(seu, idents = "Epithelial", invert = T)
  counts <- GetAssayData(seu, assay = "RNA", slot = "counts")
  coords <- seu@meta.data[,c("CenterX_global_px", "CenterY_global_px")]
  coords <- as.matrix(coords)
  spe <- SpatialExperiment(
  assays = list(counts = counts),
  spatialCoords = coords,
  colData = seu@meta.data)
  rowData(spe)$gene_name <- rownames(spe)
  #do nnSVG workflow
  #spe <- filter_genes(spe)
  spe <- computeLibraryFactors(spe)
  spe <- logNormCounts(spe)
  X <- model.matrix(~ colData(spe)$AUCell_SPP1) 
  assayNames(spe)
  set.seed(123)
  spe <- nnSVG(spe, n_threads = 8, verbose = TRUE, X = X)

  print(rowData(spe)[order(rowData(spe)$rank)[1:10], ])
  print(table(rowData(spe)$padj <= 0.05))
    
  svg_res <- rowData(spe)[order(rowData(spe)$rank), ]

  # Convert to data.frame and add 'sample' column
  df_svg <- as.data.frame(svg_res)
  df_svg$sample <- fov

  # Store in the list
  final_df[[fov]] <- df_svg

  write.csv(svg_res, paste0(
      '~', fov,
      '_nnsvg_noepi_nonGeneFilter_panCKEpi.csv'
    ))
}


#---------------------#
#compare the mean of ranks between the two conditions
#----
folder_path <- "~"  # replace with your actual path
# Get all files starting with "FOV" and ending in ".csv"
responder_file_list <- list.files(path = folder_path, pattern = "Responder.*_noepi_nonGeneFilter_panCKEpi\\.csv$", full.names = TRUE)
nonresponder_file_list <- list.files(path = folder_path, pattern = "Non-responder.*_noepi_nonGeneFilter_panCKEpi\\.csv$", full.names = TRUE)

# Read all CSV files into a list
responder_csv_list <- lapply(responder_file_list, read.csv)
nonresponder_csv_list <- lapply(nonresponder_file_list, read.csv)

#add a column to each read in dataframe
responder_csv_list <- lapply(responder_csv_list, function(df) {
  df$condition <- "Responder"
  return(df)
})
nonresponder_csv_list <- lapply(nonresponder_csv_list, function(df) {
  df$condition <- "Non_responder"
  return(df)
})

#merge 8 sampke into one big df
sample_df <- do.call(rbind, c(responder_csv_list, nonresponder_csv_list))


#use mean not median rank
summary_df <- sample_df %>%
  group_by(gene_name) %>%
  summarise(
    mean_rank_responder = mean(rank[condition == "Responder"]),
    mean_rank_nonresponder = mean(rank[condition == "Non_responder"]),
    mean_diff = mean_rank_nonresponder - mean_rank_responder,
    ratio_diff = ifelse(mean_rank_responder != 0,
                        (mean_rank_nonresponder - mean_rank_responder) / mean_rank_responder,
                        NA_real_),
    pval = tryCatch(
      wilcox.test(rank[condition == "Responder"],
                  rank[condition == "Non_responder"])$p.value,
      error = function(e) NA_real_
    ),
    .groups = "drop"
  )

write.csv(summary_df, file = "~/finalSummary_nnsvg_noepi_nonGeneFilter_longitude.csv")
```

