from pathlib import Path

import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import scanpy as sc
import squidpy as sq

import pandas as pd

sc.logging.print_header()

#---------------------------------
#read in the processed h5ad object
adata_pro = sc.read_h5ad("~/23_8_6_CosMx_longitudinal.h5ad")

#---
#read in the metadata generated by Seurat analysis
seurat_aucell_meta = pd.read_csv("~/metadta.csv")

#---
#map the annotation to the anndata obj
seurat_aucell_meta = seurat_aucell_meta.loc[adata.obs_names]

adata.obs["AUCell_SPP1"] = seurat_aucell_meta["AUCell_SPP1"]
adata.obs["SPP1_status"] = seurat_aucell_meta["SPP1_status"]
adata.obs["AUCell"] = seurat_aucell_meta["AUCell"]

#---
adata_subset = adata_pro[adata_pro.obs.fov == "75"].copy()
sq.gr.co_occurrence(
    adata_subset,
    cluster_key="AUCell_SPP1",
)
sq.pl.co_occurrence(
    adata_subset,
    cluster_key="AUCell_SPP1",
    clusters="Myeloid_SPP1+",
    save="~/cooc_baseline_nonres_fov75.pdf"
)
